server:
  port: 8888

spring:
    cloud:
       config:
         server:
              git:
                 uri: https://github.com/annie-bot/microservice-repo
                 search-paths: fornecedor